#!/usr/bin/perl -w
# usage: Link this script as ping_[ipaddr]

use strict;

my $host = $0;
#$host =~ s/.*ping_([\d\.]{8,15})$/$1/;
$host =~ s/.*ping_(\S+)$/$1/;

if (@ARGV && $ARGV[0] eq 'config') {
	my $name = $host;
	$name =~ tr/./_/;
	print <<CONFIG;
graph_title Ping response time $host
graph_vlabel time (ms)
graph_args --base 1000 -l 0
graph_scale no
graph_category network-latency
$name.label Ping for $host
CONFIG

	print "$name.label $host\n";
}

else {
	@ENV{qw(PATH)} = qw(/bin);

	my $name = $host;
	$name =~ tr/./_/;
	my @ping = qx(/bin/ping -i 0.3 -nc5 $host 2>/dev/null);
	my $times = $ping[-1];
	my $val = '';
	# second term is avg
	if ($times =~ m{^rtt min/avg/max/mdev = [\d\.]+\/([\d\.]+)}) {
		$val = $1;
	} else {
		$val = 1000;
	}
	print "$name.value $val\n";
}

